CREATE OR REPLACE FUNCTION revision_moto()
  RETURNS TRIGGER 
  LANGUAGE PLPGSQL
  AS
$$
DECLARE
BEGIN

  IF NEW.moto_reparacion = 'SI' THEN
    INSERT INTO REVISIONMOTO VALUES (OLD.moto_id, OLD.moto_id, now() + '48 hr', 20, 0, 'PENDIENTE');
    RETURN NEW;
  END IF;
RETURN NEW;
END;
$$

CREATE OR REPLACE TRIGGER revision_moto
  AFTER UPDATE
  ON MOTOCICLETA
  FOR EACH ROW
  EXECUTE PROCEDURE revision_moto();