CREATE OR REPLACE FUNCTION revision_motoi()
  RETURNS TRIGGER 
  LANGUAGE PLPGSQL
  AS
$$
DECLARE
BEGIN

  IF NEW.moto_reparacion = 'SI' THEN
    INSERT INTO REVISIONMOTO VALUES (NEW.moto_id, NEW.moto_id, now() + '48 hr', 20, 0, 'PENDIENTE');
    RETURN NEW;
  END IF;
RETURN NEW;
END;
$$

CREATE OR REPLACE TRIGGER revision_motoi
  AFTER INSERT
  ON MOTOCICLETA
  FOR EACH ROW
  EXECUTE PROCEDURE revision_motoi();